### ISSUE TITLE
Include a Python Lib

### ISSUE THREAD

**Issue by miferco97** [aerostack2/motion_reference_handlers#7]
Create a python lib for ease the use of motion reference handlers inside python code.

We could duplicate the same functionality in .cpp and python or try to use something like Pybind for having only one implementation

**Comment by miferco97** [comment]
for creating a package that contains python and cpp nodes and libs we can have a look to [Crazyflie_platform](https://github.com/aerostack2-developers/crazyflie_platform)

**Comment by pariaspe** [comment]
done in #8
